# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HarryPotterLab-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HarryPotterLab-iOS
  pod 'SwiftLint'

  target 'HarryPotterLab-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HarryPotterLab-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HarryPotterLab_Widget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HarryPotterLab_Widget

end
